M48
; DRILL file {KiCad (6.0.7)} date Sun Sep 18 15:45:41 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-18T15:45:41+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X3.4724Y-7.2657
X3.4764Y-0.8307
X6.2992Y-7.2717
X6.3031Y-0.8317
T2
X6.1102Y-2.7823
T0
M30
